# FOR LOCAL TESTING

version: "3.9"

services:
  db:
    container_name: social-network-pgdb
    image: social-network-db:latest
    build:
      context: ./postgresDocker
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  server:
    container_name: social-network-app-server
    image: social-network-server:latest
    build:
      context: ./SocialNetworkApp
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=social-network-pgdb;Username=postgres;Password=postgres;Port=5432;Database=social_network_test_db;"
      Properties__SeedData: true
    ports:
      - "8000:8000"
    depends_on:
      - db
