apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-network-app-server-dep
  labels:
    app: social-network-app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-network-app-server
  template:
    metadata:
      labels:
        app: social-network-app-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: social-network-app-server
        image: ghcr.io/tmatej/social-network-server-mssql:latest
        # image: ghcr.io/tmatej/social-network-server:latest
        ports:
        - containerPort: 5000
        env:     
        # - name: ASPNETCORE_HTTPS_PORT
        #   value: "5001"  
        - name: Properties__SeedData
          value: "true"                                                             
        - name: ConnectionStrings__postgres
          # valueFrom:
          #   secretKeyRef:
          #     name: snas-postgres-db-secret
          #     key: connectionString
          valueFrom:
            secretKeyRef:
              name: snas-postgres-cluster-db-secret
              key: connectionString
        - name: ConnectionStrings__mssql
          valueFrom:
            secretKeyRef:
              name: snas-mssql-db-secret
              key: connectionString
      imagePullSecrets:
      - name: github-registry-access-token
