apiVersion: v1
kind: Service
metadata:
  name: social-network-pgdb-svc
spec:
  selector:
    app: social-network-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
