apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-network-db-dep
  labels:
    app: social-network-db
spec:
  replicas: 1
  selector:
     matchLabels:
       app: social-network-db
  template:
    metadata:
      labels:
        app: social-network-db
    spec:
      terminationGracePeriodSeconds: 30
      hostname: social-network-db-mssql
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
      containers:
      - name: mssql
        image: cerit.io/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: social-network-db-data
