apiVersion: v1
kind: Service
metadata:
  name: social-network-db-svc
spec:
  selector:
    app: social-network-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
