# FOR LOCAL TESTING

version: "3.9"

services:
  db:
    container_name: pgdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: social-network-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  server:
    container_name: social-network-app-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: social-network-db
      POSTGRES_HOST: pgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
