# FOR LOCAL TESTING

version: "3.9"

services:
  db:
    container_name: pgdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  server:
    container_name: social-network-app-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DefaultConnection: "Host=pgdb;Username=postgres;Password=postgres;Port=5432;Database=social-network-test-db;"
    ports:
      - "8000:8000"
    depends_on:
      - db
