# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
        - opened
        - edited
        - synchronize
        - reopened
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: mcr.microsoft.com/dotnet/sdk:6.0
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SocialNetworkApp
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: SocialNetworkApp
  
  test:
 
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: mcr.microsoft.com/dotnet/sdk:6.0
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        #ports:
        #  - 5432:5432

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SocialNetworkApp
 
    - name: Build
      run: dotnet build --no-restore
      env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
      working-directory: SocialNetworkApp
      
    - name: Run Unit-tests
      run: dotnet test --no-build --verbosity normal
      working-directory: SocialNetworkApp/DalUnitTests
      
    - name: Run Infrastructure-tests
      run: dotnet test --no-build --verbosity normal
      working-directory: SocialNetworkApp/Infrastructure.EFCore.Test  
      
    - name: Run Service-tests
      run: dotnet test --no-build --verbosity normal
      working-directory: SocialNetworkApp/ServiceTests
      
